# Generated by Django 3.1.3 on 2020-12-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='clg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='regno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='state',
            field=models.CharField(choices=[('choose', 'CHOOSE'), ('tamilnadu', 'TAMILNADU')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='zipcode',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
